# -*- encoding: utf-8 -*-
#
=begin
#RepoMicroservices

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2017-08-22T19:04:01Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "nulib_microservices/version"

Gem::Specification.new do |s|
  s.name        = "nulib_microservices"
  s.version     = NulibMicroservices::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Michael B. Klein"]
  s.email       = ["michael.klein@northwestern.edu"]
  s.homepage    = "http://github.com/nulib/microservices"
  s.summary     = "A ruby wrapper for NULIB Repo Microservices on Amazon AWS"
  s.description = "No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)"
  s.license     = "Apache2"
  s.required_ruby_version = ">= 2.3"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = `find *`.split("\n").uniq.sort.select{|f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
