=begin
#RepoMicroservices

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2017-08-22T19:04:01Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NulibMicroservices::MintIdResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MintIdResponse' do
  before do
    # run before each test
    @instance = NulibMicroservices::MintIdResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MintIdResponse' do
    it 'should create an instance of MintIdResponse' do
      expect(@instance).to be_instance_of(NulibMicroservices::MintIdResponse)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

