=begin
#RepoMicroservices

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2017-08-22T19:04:01Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'nulib_microservices/api_client'
require 'nulib_microservices/api_error'
require 'nulib_microservices/version'
require 'nulib_microservices/configuration'

# Models
require 'nulib_microservices/models/mint_id_response'

# APIs
require 'nulib_microservices/api/default_api'

module NulibMicroservices
  class << self
    # Customize default settings for the SDK using block.
    #   NulibMicroservices.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
